config/routes.rb
Rails.application.routes.draw do

  get 'access/index'
  get 'access/login'
  get 'access/logout' => 'access#logout'
  post 'access/login' => 'access#attempt_login'

  root 'bubbles#index'

  resources :bubbles

end

app/models/bubble.rb
class Bubble < ActiveRecord::Base
  has_secure_password
  validates :name, :presence => true, :length => {:within => 4...12}, :uniqueness => true
  validates_length_of :feeling, :maximum => 30
  # to configure a different table name
  # Don't forget CamelCase vs  _
  # self.table_name = "super_bubbles"

  #attr_accessor already done for attributes names
  scope :np, lambda {|name| where(["name LIKE ?","%#{query}%"])}
end

app/controllers/access_controller.rb
class AccessController < ApplicationController
  before_action :confirm_logged_in,
    :except => [:login, :attempt_login, :logout]
  def index
    #display things
  end

  def login
    #login form
  end

  def attempt_login
    if params[:name].present? && params[:password].present?
      found_user = Bubble.where(:name => params[:name]).first
      if found_user
        authorized_user = found_user.authenticate(params[:password])
      end
    end
    if authorized_user
      #Mark user as logged in
      session[:bubble_id] = authorized_user.id
      session[:name] = authorized_user.name

      flash[:notice] = t :you_are_now_logged_in
      redirect_to bubbles_path
    else
      flash[:notice] = t :invalid_password_name_combination
      render 'login'
    end
  end

  def logout
    #mark user as logout
    session[:bubble_id] = nil
    session[:name] = nil
    flash[:notice] = t :you_are_now_logged_out
    redirect_to '#'
  end

  private

  def confirm_logged_in
    unless session[:bubble_id]
      flash[:notice] = t :please_log_in
      redirect_to access_login_path
      return false
    else
      return true
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_locale


	def set_locale
    #If not set up in params, find it via IP
  		I18n.locale = params[:locale] || I18n.locale
      @locale = I18n.locale
	end



  #Overriding default url options in order to always pass the locale in the url
  def default_url_options(options={})
    logger.debug "default_url_options is passed options: #{options.inspect}\n"
    { locale: I18n.locale }
  end

end

app/controllers/bubbles_controller.rb
class BubblesController < ApplicationController

#layout "admin"

  def index
    @bubbles = Bubble.all
    render 'index'
  end

  def new
    @bubble = Bubble.new
  end

  def add
    @buble= Bubble.new
  end

  def create
    @bubble = Bubble.new(bubble_params)
    if @bubble.save
      redirect_to bubbles_path
      flash[:notice] = t('bubbles.new.bubble_created_successfully', name: @bubble.name )
    else
      flash[:error] = t(:subject_creation_error)
      render('new')
    end
  end

  def bubble_params
    params.require(:bubble).permit(:name, :feeling, :password, :password_confirmation)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @locale = I18n.locale
    render 'index'

  end

  def new
    render 'new'
  end

end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_message_for(object)
    render 'application/error_message', :object => object
  end

  def logged_in
    unless session[:bubble_id]
      return false
    else
      return {:name => session[:name]}
    end
  end
end

app/helpers/bubbles_helper.rb
module BubblesHelper

  #example from ruby essentials that adds the good tag depending on the status
  def status_tag(integer, options={})
    options[:text] ||= ''
    if integer.even?
      content_tag(:span, options[:text], :class => 'status-even')
    else
      content_tag(:span, options[:text], :class => 'status-odd')
    end
  end

  def set_selected_l
    if I18n.locale == :en then
      return {:fr_c => '', :en_c => 'pure-menu-selected'}
    else
      return {:fr_c =>'pure-menu-selected', :en_c => ''}
    end
  end

end

app/views/access/index.html.erb
<h1>Access#index</h1>
<p>Find me in app/views/access/index.html.erb</p>

app/views/access/login.html.haml
.pure-g
  .pure-u-1-5
  .pure-u-3-5.small-box-shadow
    =form_tag 'login', :class => "pure-form pure-form-stacked" do
      %fieldset
        %legend= t :please_log_in
        =label_tag t :name
        =text_field_tag :name
        %br/
        =label_tag t :password
        =password_field_tag :password
        %br/
        =submit_tag t :log_in, :class => "pure-button"
  .pure-u-1-5

app/views/application/_error_message.html.haml
-if object && object.errors.size >0
  #errorExplanation
    %h2= object.errors.size.to_s + ' ' + t('common.error', count: object.errors.size)
    %ul
      -object.errors.full_messages.each do |msg|
        %li= msg

app/views/application/_footer_bar.html.haml
%hr/
= params.inspect
= @locale.inspect
= @fr_class.inspect
= @en_class.inspect

app/views/application/_menu_bar.html.haml
.pure-menu.pure-menu-open.pure-menu-horizontal
  = link_to t(:localize_app), bubbles_path, class:"pure-menu-heading"
  = l Time.now, :format => :long
  %ul
    %li{:class => set_selected_l[:en_c]}
      = link_to t(:en_lang), {locale: 'en'}
    %li{:class => set_selected_l[:fr_c]}
      = link_to t(:fr_lang), {locale: 'fr'}
    %li
      -if logged_in
        = t :welcome_user,logged_in
        %li= link_to t(:log_out), access_logout_path
      -else
        = t :not_logged_in
        %li= link_to t(:log_in), access_login_path
.notice= flash[:notice] if !flash[:notice].blank?
%br/

app/views/bubbles/index.html.haml
.pure-g
  .pure-u-1-5
  .pure-u-3-5
    = error_message_for(@bubble)
    %h2= t '.bubbles_display', count: @bubbles.size
    %table.pure-table.pure-table-bordered
      %thead
        %tr
          %th #
          %th= t 'activerecord.attributes.bubble.name'
          %th= t 'activerecord.attributes.bubble.feeling'
      %tbody
        - @bubbles.each do |bubble|
          %tr
            %th= status_tag(bubble.id,{:text => bubble.id.to_s})
            %th= bubble.name
            %th= bubble.feeling
    %p= link_to t('.want_new_one'), new_bubble_path, class: "pure-button pure-button-primary"
  .pure-u-1-5

app/views/bubbles/new.html.haml
.pure-g
  .pure-u-1-5
  .pure-u-3-5.small-box-shadow
    = error_message_for(@bubble)
    = form_for @bubble, :html => {:class => "pure-form pure-form-stacked"} do |f|
      %fieldset
        %legend= t '.new_bubble'
        / .pure-control-group
        = f.label :name
        = f.text_field :name, placeholder: "Bubbly ?"
        / .pure-control-group
        = f.label :feeling
        = f.text_area :feeling
        / .pure-controls
        = f.label t :password
        = f.password_field :password
        = f.label t :repeat_password
        = f.password_field :password_confirmation
        = f.submit t('.submit_new_one'), :class => "pure-button pure-button-primary"
        / .pure-controls
        = link_to t('.back_to_index'), bubbles_path, class: "pure-button"
  .pure-u-1-5

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>I18n Test ! ADMIN SECTION</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <h3>Admin Page </h3>
<!-- before yield -->
<%= yield %>
<!-- after yield  -->
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>I18n Test !</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'application/menu_bar' %>
<!-- before yield -->
<%= yield %>
<!-- after yield  -->
<%= render 'application/footer_bar' %>
</body>
</html>